name: Setup Plural
description: Sets up the plural cli in your github repo
inputs:
  config:
    description: Plural Config File
    required: true
  vsn:
    description: the plural cli version to use
    required: false
    default: '0.5.18'
  plat:
    description: the cli platform to specify
    required: false
    default: 'amd64'
outputs: {}
runs:
  using: 'node12'
  main: 'index.js'