name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12"
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Test downloading plural
        uses: ./
        with:
          config: ${{ secrets.PLURAL_CONF }}